### PR TITLE
Major style and code refactoring 

### PR DESCRIPTION
**Pull request by eyingxuan**
This PR is a refactoring of most of our code base to conform to the ESLint rules introduced to promote consistency and better style, which will hopefully make the code base easier to understand and less error-prone. In particular, the most significant change, style-wise (except for indentation) is the use of the object destructuring syntax for component props and state, as well as the introduction of PropTypes verification for each component. 

The following are some comments I have and notable changes I made. 

- Keep note that we should not, in most circumstances, extract information from props and store it as component state to prevent stale state. 
- Each `<li>` in SectionDisplay.js (which represents a bar with information for a section) is entirely clickable instead of clickable only on where there is text present. 
- sectionInfo displayed in SectionInfoDisplay is **not** connected to our backend and will always display 
CIS 110 data. It is also never updated based on the section selected (as we only have CIS 110s)
- Take note that when we start writing backend code, we consider how to handle missing reviews/difficulty ratings, and accurately represent them in our frontend code. Props validation is a start, but we should handle what happens when, for example, in summary.js meetHour or hourLength is missing. 
- SearchResults sort by quality, difficulty etc. has not been implemented. 
- search_result.js props structure is unclear and will depend on how the backend is built. Props validation is ambiguous on purpose. 
- Props validation is unimplemented for searchFilter.js as well on purpose as filter feature is not built. 
- OutClickable class requires the method `collapse` to be implemented by any class that extends it. Even though it works, this is not the cleanest method to achieve the feature. It is possible to rewrite the component in a better way. Further, I recommend that dropdown.js be refactored in a separate PR later on. Note that props validation have not be implemented for this file. 
- Modals in general are also not implemented in the cleanest way. They should be refactored in a separate PR and use render props/higher-order-components. 

- [x] /selector
- [x] /reducers
- [x] /search
- [x] /modals
- [x] /actions
- [x] dropdown.js, App.js

### CODE REVIEW

**Comment by eyingxuan** [comment]
I'm nearly done with the refactoring! Just documenting some thoughts down on the way.

**Review by davish — COMMENTED** [review]
This looks great so far! The one question I had was on one of the bullet points:
> sectionInfo displayed in SectionInfoDisplay is not connected to our backend and will always display
CIS 110 data. It is also never updated based on the section selected

Was this just a note on how `sectionInfo` currently works, and something that needs to get improved on going forward?

Also, let me know if you'd like me to help on refactoring some of those other directories, if that would make things easier for you!

**Comment by eyingxuan** [comment]
That was just a note on how `sectionInfo` currently works. Before we connected the search to the current backend, we were just accessing data from a hard coded js file, so I presume we just haven't gotten around to change how sectionInfo works.

**Review by davish — CHANGES_REQUESTED** [review]
Great work!! Some things I noticed when running locally:

First, dropdown styling seems to be a bit off; each element is a dark grey, even when it's not being moused over:
image

Second, two minor things in the section list:
image
Sections which are in the schedule shouldn't be faded out, even though they "conflict" with something in the schedule. In this example, 202 shouldn't be faded, and 203 should still be faded. Also, there seems to be a slight offset in the spacing of the green box when a course has been added to the schedule. I think it has to do with the difference in width between an `x` and a `+` icon.

But besides those small things, really looks great! The code is definitely a lot cleaner now.

**Review by davish — APPROVED** [review]

**Comment by davish** [comment]
Looks good! I made a small visual change in the footer, but everything else looks great.

**Comment by eyingxuan** [comment]
Done with the refactoring! ESLint reports 0 errors! This is ready to be merged.

**Comment by davish** [comment]
woohoo!

**Pull request merged**
